### ISSUE TITLE
Doors changing cardinal directions in Delvedit

### ISSUE THREAD

**Issue by SuperPinger** [Interrupt/delverengine#156] opened 2020-10-22 20:24 UTC
When placing many doors around in Delvedit, they can start changing cardinal directions on their own and/or have different cardinal directions in-game as opposed to in-editor.

**Comment by PythooonUser** [comment] 2020-10-23 13:01
I can confirm that behavior. The rotation of doors is reset whenever you either add a new entity (not marker) or change the terrain.

![Door-Rotation-Reset2](https://user-images.githubusercontent.com/13063023/97006656-792cc700-1540-11eb-9896-6d0e543cd0fe.gif)

![Door-Rotation-Reset](https://user-images.githubusercontent.com/13063023/97006657-79c55d80-1540-11eb-97ea-56f6567a6f59.gif)

**Comment by PythooonUser** [comment] 2020-10-23 13:07
The second problem of changed door rotations i-game vs. in-editor is very erratic and I couldn't yet find any indication of a pattern. Sometimes it works, sometimes not. Tiles do not seems to have an effect (if changed the level layout e.g.).

**Comment by PythooonUser** [comment] 2020-10-28 15:42
Sadly, this issue will probably be a *won't fix*. Altering the above behavior will cause a lot of compatibility issues with existing levels (in the base Delver game).

As a workaround, you can place a door **entity** instead of a prefab, which should keep its orientation.

However, in general, you should not worry too much about a doors orientation, because the game will make sure when a level gets loaded, that doors have a valid orientation. When determining that orientation, it sometimes comes to other conclusions than what you set in the editor.

**Closed** 2020-11-10 16:43 UTC
Labels: wontfix
